server:
  # toggles a graphql web api explorer at /api (disable for prod instances)
  graphiql: true
  address: 0.0.0.0:1234
  # location of the frontend
  public_dir: ./public
  index_file: index.html

  # if you want to serve photos via https, you need to set this to true
  # and specify the paths to your certificate and key
  ssl: false
  key: cert/key.pem
  cert: cert/cert.pem

# the following are the defaults and should work in most cases
# but if you have different locations for the library and database
# file, you need to set the appropriate paths to those
photos:
  library: "~/Pictures/Photos Library.photoslibrary"
  # don't worry this is opened in read only mode
  database: "~/Pictures/Photos Library.photoslibrary/database/Photos.sqlite"
  # These are the default directories where Photos.app stores media files
  originals: originals
  renders: resources/renders
  resized: resources/derivatives
  thumbs: resources/derivatives/masters

# this database is used internally and is created automatically
app:
  database: xpoz.sqlite

media:
  # Flip this to true to make transcoded copies of your videos which are
  # suitable for displaying in a browser (AAC/h.264 mp4)
  # (original videos are left intact)
  transcode_videos: false
  # The number of simultaneous ffmpeg worker processes
  workers: 4
  # By default the transcoded videos are stored in here (relative to the binary)
  videos_path: ./videos
  # you need to have ffmpeg installed with appropriate codecs if you enable
  # video transcoding
  ffmpeg:
    bin: ffmpeg
    probe: ffprobe
    # these arguments are used when transcoding a sdr video
    sdr:
      - -c:v
      - h264
      - -crf
      - 34
      - -vf
      - fps=30
    # arguments passed to ffmpeg whan transcoding a hdr video
    # by default it tries to use tone mapping to preserve the original colors
    # as much as possible
    hdr:
      - -c:v
      - h264
      - -crf
      - 34
      - -vf
      - zscale=t=linear:npl=100,format=gbrpf32le,zscale=p=bt709,tonemap=tonemap=hable:desat=0,zscale=t=bt709:m=bt709:r=tv,format=yuv420p,fps=30
